### PR TITLE
implement Selenium 4 CDP support

### PR DESCRIPTION
**Pull request by MoLow**
Hi @vania-pooh,
This is an implementation of supporting new selenium 4 cdp proxying. 
a new selenium 4 grid is able to proxy CDP WebSocket from the node through the hub out of the box, So I wanted to have this possibility in GGR as well - as we use GGR and it works great for us.
it is pretty much based on VNC, with some tweaks.

Please let me know what I should do to get this PR approved and merged - if there are any documentation/tests missing etc.

### CODE REVIEW

**Comment by vania-pooh** [comment]
@MoLow this is not standard WebDriver and may change in the future. So I don't think we'll merge this.

**Comment by MoLow** [comment]
> @MoLow this is not standard WebDriver and may change in the future. So I don't think we'll merge this.

thanks @vania-pooh 
I am not sure about your comment, since also these are not standard: https://github.com/testimio/ggr/blob/master/proxy.go#L54-L58
what will be the downside of adding this?

**Comment by vania-pooh** [comment]
@aandryashin could you please take a look?

**Comment by vania-pooh** [comment]
@MoLow the problem with this change is that we don't control these capabilities. What if several months later guys from Selenium team decide to change the name of the capability like they did with `/file` API (https://github.com/aerokube/selenoid/issues/1079)? Yes, Ggr supports some non-standard APIs like you mentioned above but they are under our control.

**Comment by MoLow** [comment]
> @MoLow the problem with this change is that we don't control these capabilities. What if several months later guys from Selenium team decide to change the name of the capability like they did with `/file` API ([aerokube/selenoid#1079](https://github.com/aerokube/selenoid/issues/1079))? Yes, Ggr supports some non-standard APIs like you mentioned above but they are under our control.

I would be grateful if you will consider adding this, as I think essentially it is not really different than the non-standard API's already supported. I will totally respect if you decide not to add support for this, and we will have to build and use our own fork.

thanks

**Comment by MoLow** [comment]
> @MoLow
> 
> Also Selenium guys consider Selenium Grid 4 fault-tolerant solution. How about just using it instead of Ggr?
@vania-pooh I took a look at that and still think that GGR is a much better solution as it is stateless

**Pull request closed without merging**
