### PR TITLE
Capabilities based auth

### PR DESCRIPTION
**Pull request by adrichem**
This PR allows Selenium WebDriver on .Net to access ggr. 

Microsoft .Net silently discards the username and password from the URL, presumably due to RFC 3986. So we allow the username and password to be transmitted as part of the desiredCapabilities JSON.

### CODE REVIEW

**Comment by vania-pooh** [comment]
@adrichem I investigated the situation with .NET Selenium driver and can state that:
1) Currently basic HTTP authentication is not supported in Selenium client but **is** supported in .NET. For example take a look at these classes:

* https://msdn.microsoft.com/en-us/library/system.uri.userinfo.aspx - it is possible to parse text URL and extract `username:password` pair.
* It is possible to set credentials as request property here: https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.credentials(v=vs.110).aspx
2) Saucelabs implements authentication exactly in the same way you did via capabilities whereas for other platforms it is using just basic HTTP auth url.

So I think it would be better to support authentication directly in client instead of introducing hacky capabilities to Ggr. I would introduce these changes here: https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/CommandInfo.cs#L102-L103

I even found a PR with exactly the same changes I'm proposing: https://github.com/SeleniumHQ/selenium/pull/3669

**Comment by adrichem** [comment]
@vania-pooh Thanks for the feedback. I will close this PR. I do have one more question: How do you feel about allowing GGR to accept sessions without authentication? Something like “if user cannot be determined from basic authentication, then use a default quota file to route the session” I assume it’s a relatively small change and compatible with the philosophy of GGR?

**Comment by vania-pooh** [comment]
@adrichem I think we could implement something like the following:
1) If no credentials are provided - then check whether `guest.xml` file exists (guest quota name can be specified as parameter, default is `guest`) in quota directory.
2) If it exists - the use this quota.
3) If it does not exist - return error: `Guest access is unavailable.`.

But what is the use case for that in your opinion? In my opinion this feature could be used to organize some sandbox quota with limited number of browsers available where newcomers can learn how to work with Selenium and then request personal quota.

**Comment by adrichem** [comment]
@vania-pooh My use case is that I will use GGR to route to different hubs based on type and version of browser. The hubs  have different servlets and port numbers will change sometimes. So GGR looks very useful. However, I don’t need basic authentication as a VPN authenticates and encrypts. 
Because of  https://github.com/SeleniumHQ/selenium/pull/3669 our tests currently can’t connect to GGR. Also https://github.com/SeleniumHQ/selenium/issues/3808 must be fixed before we can upgrade our Selenium version.

**Pull request closed without merging**
