### PR TITLE
Allow use of https on ggr

### PR DESCRIPTION
**Pull request by brunosccosta**
Adding an extra option `-ssl` to setup ggr as https://
To use this option, one need to add -certFile and -keyFile
pointing to `cert.pem` and `key.pem`.

Example:
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout key.pem -out cert.pem
./ggr -verbose -guests-allowed -ssl -certFile cert.pem -keyFile key.pem

### CODE REVIEW

**Comment by vania-pooh** [comment]
@brunosccosta I would not complicate Ggr with SSL support. In the majority of cases Ggr has multiple instances in several datacenters and the traffic is balanced across these instances using Nginx or another lightweight reverse proxy server. So I personally think that this is Nginx responsibility to work with certificates. In the minimal installation nothing prevents you from starting an Nginx container with SSL config on the same host.
@aandryashin any thoughts?

**Comment by lanwen** [comment]
It can be also https://caddyserver.com/

**Comment by brunosccosta** [comment]
Hey guys! 

As usual, there are more than one way to do it and using go itself could be as good as any other. I should have created an issue first so we could discuss this instead of hacking a solution, but it ended up being quite simple and i decided to send this PR, but please, feel free to close it if you think this is not useful.

I have anything else to add in the future, i'll create an issue first :)

Thanks for this great project btw!

**Comment by vania-pooh** [comment]
@brunosccosta yes, will close it for now. Anyway thank you for your work and next time let's discuss possible features in issue first - we are open for proposals.

**Pull request closed without merging**
