### PR TITLE
Added support of a custom request id for logging

### PR DESCRIPTION
**Pull request by gsx95**
Adds ability to associate a specific ggr log message with the original WebDriver request.

Use: User puts a custom request id into the Desired Capabilities of his WebDriver, ggr logs the id and lets the user associate the log message with his original request.

### CODE REVIEW

**Comment by vania-pooh** [comment]
@gsx95 how about using sessionID and requestID to get the logs? This change breaks 10-column logging layout used in our ELK configs.

**Comment by mdrobek** [comment]
The goal is to identify those logs, which DO NOT contain a (GridRouter or Selenoid) SessionID, cause a Session couldn't be established (e.g., UNSUPPORTED_BROWSER, ....).

We can't find any Client-Request-ID in the logging lines (e.g., proxy.go, line 277), which has to be defined from the requesting client side.
We would expect to enrich your capabilities in a way, so that the client can define a Request-ID, which will be logged. So in case of an unsuccessful attempt to create a (GridRouter, Selenoid) session, one would be able to map those logs to the respective client logs (via client request ID).

Any feedback would be highly appreciated.

**Comment by vania-pooh** [comment]
@gsx95 take a look at an example `SESSION_FAILED` request:
```
2018/03/29 12:56:15 [123456] [10.22s] [SESSION_FAILED] [my-quota] [192.168.0.1] [firefox-47.0] [hub-host.example.com:4444] [-] [1] [Error forwarding the new session Request timed out waiting for a node to become available.]
```
Here we have: `[123456]` which is a counter incrementing for every request. You can find the remaining `SESSION_ATTEMPTED` messages by grepping your logs by this ID, e.g.:
```
$ docker logs ggr 2>&1 | grep 123456
```
This as well as error message from the last host should be enough to diagnose the problem.

**Comment by mdrobek** [comment]
@vania-pooh This SessionID is fine to track logs only from GridRouter or Selenoid. However, you cannot match GridRouter logs (that have a self-generated incrementing SessionCounterID) with external client side logs.

Suppose you want to match all GridRouter logs with the outside client logs?
How would you do that, if on the client-side, which generates the request to GridRouter, you are not able to see the GridRouter SessionID in case of a failed session.
Its not about debugging GridRouter, its about matching GridRouter log messages with outside client requests.

We see 2 options to tackle this issue:
1) From a GridRouter protocol side, we use the capabilities options and sent a client-side generated requestID, which will then be logged in a GridRouter log event.
2) GridRouter/Selenoid generates a unique sessionID (which does not increment, since this would be non-unique with multiple paralllel running GridRouter instances) AND forwards this unique session ID to the client-side as a response in ANY case (also FAILED session attempts).

Can u please elaborate on your thoughts of this problem?
Thank you very much for your support/help.

**Comment by vania-pooh** [comment]
Closing in favor to https://github.com/aerokube/ggr/issues/212.

**Pull request closed without merging**
